# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSalaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryfile', models.FileField(upload_to='salaryadd/%Y/%m/%d/%s')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LoadUserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfile', models.FileField(upload_to='useradd/%Y/%m/%d/%s')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('salary1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary4', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary5', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary6', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary7', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary8', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary9', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary10', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary11', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary12', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary13', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary14', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary15', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary16', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary17', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary18', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary19', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary20', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary21', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary22', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary23', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary24', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary25', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary26', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary27', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary28', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary29', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary30', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary31', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary32', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary33', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary34', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary35', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary36', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary37', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary38', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary39', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salary40', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', 'staffnum__staffnum'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('staffnum', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('idcard', models.CharField(max_length=18)),
                ('banknum', models.CharField(max_length=19)),
                ('password', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created', 'staffnum'],
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='staffnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='show.User'),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set([('staffnum', 'year', 'month')]),
        ),
    ]
