# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='month',
            new_name='salarytime',
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='year',
        ),
    ]
