# Generated by Django 2.0 on 2017-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20171214_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary1',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary10',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary11',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary12',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary13',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary14',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary15',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary16',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary17',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary18',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary19',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary2',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary20',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary21',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary22',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary23',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary24',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary25',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary26',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary27',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary28',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary29',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary3',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary30',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary31',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary32',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary33',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary34',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary35',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary36',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary37',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary38',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary39',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary4',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary40',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary5',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary6',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary7',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary8',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary9',
        ),
        migrations.AddField(
            model_name='salary',
            name='bjf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='褒奖费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='bjkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='病假扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='blgz',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='保留工资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='cdztkk',
            field=models.DecimalField(decimal_places=3, default=11, max_digits=10, verbose_name='迟到早退扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='cybjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='长夜班津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='dqlcjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='地区留才津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='dsznf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='独生子女费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='gwgt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='岗位津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='gwgz',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='岗位工资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='gzxzgrsds',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='工资薪资个人所得税'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='jbf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='加班费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='jhhj',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='结婚贺金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='jtzf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='集体房租'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='kckk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='餐费扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='kgkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='旷工扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='nggz',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='年功工资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='qynjgrjfshbk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='企业年金个人缴费税后补缴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='qynjgrjfshkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='企业年金个人缴费税后扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='qynjgrjfsqbk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='企业年金个人缴费税前补缴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='qynjgrjfsqkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='企业年金个人缴费税前扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='sfgz',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='实发工资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='shbf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='税后补发'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='shkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='税后扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='sjkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='事假扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='sqbf',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='税前补发'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='sqkk',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='税前扣款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='sybxge',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='失业保险个人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='tabc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='提案报酬'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='tgjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='特岗津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='wpjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='外派津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='xmjlj',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='项目激励金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='yanglbxgr',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='养老保险个人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='yfgz',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='应发工资'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='yilbxgr',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='医疗保险个人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='yjgz1',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='业绩工资1(OT)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='yjgz2',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='业绩工资2(OT)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='zfgjjgr',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='住房公积金个人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='zjjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='职级津贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='zjljlj',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='总经理激励金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='zwjt',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='职务津贴'),
            preserve_default=False,
        ),
    ]
